const data={
    product:[
        {
            id:'dhE0vwwTdtiNi8bPPsuQ',
            title:'Samsung Galaxy M13',
            price:10000,
            categoery:'electronics',
            image:'https://m.media-amazon.com/images/I/812YsUxpyfL._SX522_.jpg',
            quantity:10,
        },
        {
            id:'UG6e6Xa50vmXwtRdA25f',
            title:'OnePlus Nord CE 2 Lite 5',
            price:18000,
            categoery:'electronics',
            image:'https://m.media-amazon.com/images/I/71V--WZVUIL._SX522_.jpg',
            quantity:10,
        },
        {
            id:'vMv3axk3KUh3syC3KRea',
            title:'Acer 139 cm (55 inches)',
            price:33000,
            categoery:'electronics',
            image:'https://m.media-amazon.com/images/I/71kQUbJU9cL._SX522_.jpg',
            quantity:10,
        },
        {
            id:'dZohQ5jh6BqgZtiiApdL',
            title:'boAt Rockerz 450 Bluetooth On Ear Headphones with Mic',
            price:1500,
            categoery:'electronics',
            image:'https://m.media-amazon.com/images/I/51xxA+6E+xL._SX522_.jpg',
            quantity:10,
        },
        {
            id:'FJFJTda2Yy7vaiYpAXU1',
            title:'Noise Pulse Go Buzz Smart Watch ',
            price:1600,
            categoery:'electronics',
            image:'https://m.media-amazon.com/images/I/61oDV-EKLyL._SX425_.jpg',
            quantity:10,
        },
        {
            id:'T3xU6tz1M4EwE5XpARnn',
            title:'KAVIT HUB Navy Blue and Red Half Sleeve Bikers Tshirts for Men',
            price:750,
            categoery:'men',
            image:'https://m.media-amazon.com/images/I/61G0h6RUwIL._UX425_.jpg',
            quantity:10,
        },
        {
            id:'H4VpfiYuzFKjkdWDDJXI',
            title:'Men Slim Fit Printed T-Shirts',
            price:550,
            categoery:'men',
            image:'https://m.media-amazon.com/images/I/51d+XrHWXnL._UX466_.jpg',
            quantity:10,
        },
        {
            id:'vEsFL6Az4gDyCadp5vi0',
            title:'BON PRODUIT Men Normal is Boring Printed ',
            price:800,
            categoery:'men',
            image:'https://m.media-amazon.com/images/I/41N5B1q3fIL.jpg',
            quantity:10,
        },
        {
            id:'EXyiGux1CqQERq30Tju1',
            title:'Mens Regular Fit Tshirt',
            price:290,
            categoery:'men',
            image:'https://m.media-amazon.com/images/I/41Y9k2EdApL.jpg',
            quantity:10,
        },
        {
            id:'m9nnUZRJk5uL1cjLf3Ge',
            title:'Peter England Men Jeans',
            price:980,
            categoery:'men',
            image:'',
            quantity:10,
        },
        {
            id:'QBk6wg62RYi4RGu0Zm7g',
            title:'BIBA Women Salwar Suit Set',
            price:1925,
            categoery:'women',
            image:'https://m.media-amazon.com/images/I/81ojhSs8EuL._UY879_.jpg',
            quantity:10,
        },
        {
            id:'hZfetAP9WzEeJyyB6GnE',
            title:'BIBA Women Cotton Salwar Suit Set',
            price:1660,
            categoery:'women',
            image:'https://m.media-amazon.com/images/I/918o80kJQQL._UX569_.jpg',
            quantity:10,
        },
        {
            id:'RX3F5GafaJM093tczkGn',
            title:'BIBA Women Cotton Salwar Suit Set',
            price:2800,
            categoery:'women',
            image:'https://m.media-amazon.com/images/I/81UCB7dynXL._UX522_.jpg',
            quantity:10,
        },
        {
            id:'gYFK05Kzw1g5cdsz15q3',
            title:'Women Rayon Straight Golden Foil Printed Kurta with Palazzo',
            price:700,
            categoery:'women',
            image:'https://m.media-amazon.com/images/I/61hJAB-8R5S._UY679_.jpg',
            quantity:10,
        },
        {
            id:'YkhKJsnvB5Hn356rskic',
            title:'Ishin Women Cotton salwar suit set',
            price:1850,
            categoery:'women',
            image:'https://m.media-amazon.com/images/I/71Dp-FWXXxS._UX679_.jpg',
            quantity:10,
        },
        {
            id:'AA7FZKKoyKPYGfK9PtNj',
            title:'The Dahadaha Gold Ring',
            price:26276,
            categoery:'jewelery',
            image:'https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/z/ZGR00109_779.jpg',
            quantity:10,
        },
        {
            id:'RCPFJFzqoQDDeEHnp0p6',
            title:'The Berinhard Gold Ring',
            price:12533,
            categoery:'jewelery',
            image:'https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/z/ZLR00463-6_316.jpg',
            quantity:10,
        },
        {
            id:'aeskLeW94u7VTF3PJEJR',
            title:'The Domonkos Gold Ring',
            price:17552,
            categoery:'jewelery',
            image:'https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/z/ZLR00627-6_366.jpg',
            quantity:10,
        },
        {
            id:'fcb2GPw6kvuZsDixiT1C',
            title:'The Jarlath Diamond Ring',
            price:30791,
            categoery:'jewelery',
            image:'https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/g/GR00349-6_650.jpg',
            quantity:10,
        },
        {
            id:'eo26cg0YYVY73Ps8cArL',
            title:'The Merrie Diamond Ring',
            price:10240,
            categoery:'jewelery',
            image:'https://cf-cdn.pcjeweller.com/public/uploads/catalog/product/preview/l/LR00461-6_313.jpg',
            quantity:10,
        },
    
    ],
     
    myCart:[],
}
export default data;